use_frameworks!

target 'YBTableViewController_Example' do
  pod 'YBTableViewController', :path => '../'

  target 'YBTableViewController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
